name = "brandgita-react"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "brandgita-waitlist"
database_id = "c0c56a08-861b-402b-813d-cd8734e8977a"
